services:
  it-tools:
    container_name: it-tools
    restart: unless-stopped
    ports:
      - "8023:80"
    image: "corentinth/it-tools:latest"
    volumes:
      - /home/eyes/docker/it-tools:/config
    networks:
      - net

networks:
  net:
    external: true
    name: net
