services:
  server:
    image: "vaultwarden/server:latest"
    ports:
      - "8666:80"
    restart: unless-stopped
    volumes:
      - "/home/eyes/docker/vaultwarden/data/:/data/"
    container_name: vaultwarden
    networks:
      - net

networks:
  net:
    external: true
    name: net
