services:
  wg-easy:
    image: ghcr.io/wg-easy/wg-easy
    container_name: wireguard
    restart: unless-stopped
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
    cap_add:
      - SYS_MODULE
      - NET_ADMIN
    ports:
      - "51821:51821/tcp"
      - "51820:51820/udp"
    volumes:
      - "/home/eyes/docker/wireguard:/etc/wireguard"
    environment:
      - WG_PORT=51820
      - PORT=51821
      - PASSWORD_HASH=$$2a$12$$SW7J/1sbdo.UIDY0qg7bVusgrgN/bqRgiKTf66Ny3YRhhzIyuAcyC
      - WG_HOST=192.168.29.100
      - LANG=en
