services:
  agent:
    ports:
      - 9006:9001
    container_name: portainer-agent
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    image: portainer/agent:latest
    networks:
      - net

networks:
  net:
    external: true
    name: net
