services:
  freshrss:
    image: lscr.io/linuxserver/freshrss:latest
    container_name: freshrss
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kolkata
    volumes:
      - /mnt/docker/freshrss:/config
    ports:
      - 80:80
    restart: unless-stopped
    networks:
      - net

networks:
  net:
    external: true
    name: net
