services:
  windows:
    image: dockurr/windows:latest
    container_name: windows
    devices:
      - /dev/kvm
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 3389:3389/tcp
      - 3389:3389/udp
    stop_grace_period: 2m
    restart: on-failure
    volumes:
      - /mnt/docker/windows/win11x64.iso:/win11x64.iso
      - /mnt/docker/windows:/storage
      - /mnt/docker/windows/data/shared:/shared
    environment:
      VERSION: "win11"
      RAM_SIZE: "6G"
      CPU_CORES: "4"
      DISK_SIZE: "64G"
      MANUAL: "Y"
